### ISSUE TITLE
Mapping Type is not supported anymore by Elasticsearch

### ISSUE THREAD

**Issue by lubbo** [pksprojects/ElasticSwift#10]
As per official documentation:
https://www.elastic.co/guide/en/elasticsearch/reference/master/removal-of-types.html#_what_are_mapping_types

ElasticSwift is not aligned with above deprecation and some operations still use mapping type.
Es. Index and Search

**Comment by prafsoni** [comment]
Thanks for bringing this up. I will leave this open.

**Comment by prafsoni** [comment]
added deprecation warning #19
