### ISSUE TITLE
Please don't raise target platform requirements

### ISSUE THREAD

**Issue by lubbo** [pksprojects/ElasticSwift#24]
I see you are experimenting new libraries.
I kindly ask you to keep compatibility with at least the latest 3 iOS versions (at the moment 10 11 12)
Another recommendation is to avoid 3rd party libraries as much as possible, i.e. avoid Alamofire or other networking libs that are not maintained by Apple if they don't generate really great huge benefits, it would be a pain to maintain on OS upgrade.

Thanks for the great work you are doing!

**Comment by prafsoni** [comment]
Totally, I am committed to no dependencies unless required. The reason to raise the target platform requirements is cocoapod which doesn't allow swift 5.0 for iOS < 12.2. I will do some research on it.

**Comment by prafsoni** [comment]
ok, so xcode-tools were messed up on my macbook which was causing `pod spec lint` to fail hence, not able to push pod for `iOS 10` fixed in  `v1.0.0.alpha-6`
