### ISSUE TITLE
Unit Tests - Missing asserts on real tests results

### ISSUE THREAD

**Issue by lubbo** [pksprojects/ElasticSwift#8]
In the unit tests, the tests results are not asserted.
My elastic instance is not running on localhost, so each API invocation fails but tests are reported as ended successfully.

**Comment by prafsoni** [comment]
Since Project is still in alpha unit tests are not very reliable. As ElasticSwift moves to beta, more unit tests and assertions will start popping up. With that said, Any contributions to the project are welcome.

**Comment by prafsoni** [comment]
#19
